### ISSUE TITLE
Assign different colors to difference clusters of dot in the map

### ISSUE THREAD

**Issue by ShaoyuanTan** [acorg/Racmacs#125]
Hey Sam,

I am currently learning to use RACMACS to analysis influenza antigenic cartography. 

I see that the original h3map2004 map has difference colors, but when I plot maps, all dots are green color.   I wonder if there is a function to assign different colors to individual dots? 

Thanks for taking time to answer my question!
Shaoyuan

**Comment by davipatti** [comment]
You can use `agFill()` and `srFill()` to assign colours to antigens and sera respectively.

And `agOutline()` and `srOutline()` to colour their edges.

See the docs https://acorg.github.io/Racmacs/reference/index.html#point-plotting-styles for more details

**Comment by ShaoyuanTan** [comment]
Thank you so much, David!! This works!!

Shaoyuan
