### ISSUE TITLE
install "Racmacs" failure

### ISSUE THREAD

**Issue by ZhaoZheLin** [acorg/Racmacs#129]
hello everyone
  when i run the instruction : "devtools::install_github("acorg/Racmacs")". The Rstudio display

####################################################################################
> devtools::install_github("acorg/Racmacs")
Downloading GitHub repo acorg/Racmacs@HEAD
v  checking for file 'C:\Users\zhao\AppData\Local\Temp\Rtmp8IxFon\remotesd05c51a96f98\acorg-Racmacs-9ca81ad/DESCRIPTION' ... 
-  preparing 'Racmacs': (684ms)
v  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (492ms)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'Racmacs_1.1.35.tar.gz'
   
将程序包安装入‘C:/Users/zhao/Documents/R/win-library/4.1’
(因为‘lib’没有被指定)
* installing *source* package 'Racmacs' ...
** using staged installation
** libs

*** arch - i386
"c:/rtools40/mingw32/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-41~1.2/include" -DNDEBUG -DSTRICT_R_HEADERS -I'C:/Users/zhao/Documents/R/win-library/4.1/Rcpp/include' -I'C:/Users/zhao/Documents/R/win-library/4.1/RcppArmadillo/include' -I'C:/Users/zhao/Documents/R/win-library/4.1/RcppProgress/include' -I'C:/Users/zhao/Documents/R/win-library/4.1/RcppEnsmallen/include' -I'C:/Users/zhao/Documents/R/win-library/4.1/rapidjsonr/include'     -fopenmp   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c Racmacs_wrappers.cpp -o Racmacs_wrappers.o
sh: line 1: c:/rtools40/mingw32/bin/g++: No such file or directory
make: *** [C:/PROGRA~1/R/R-41~1.2/etc/i386/Makeconf:245: Racmacs_wrappers.o] Error 127
ERROR: compilation failed for package 'Racmacs'
* removing 'C:/Users/zhao/Documents/R/win-library/4.1/Racmacs'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/zhao/AppData/Local/Temp/Rtmp8IxFon/filed05c48ea6c9b/Racmacs_1.1.35.tar.gz’ had non-zero exit status
#####################################################################################

  SO how can i install the package?

 Best wishes

**Comment by drserajames** [comment]
The previous user did solve it as they submitted another issue.

You need to have g++ installed - there are instructions on for macs [here](https://github.com/acorg/Racmacs) - scroll down to **Installing gcc**

**Comment by shwilks** [comment]
Am going to close this issue since pre-compiled versions of Racmacs can now be installed directly from CRAN with

```
install.packages("Racmacs") 
```
