### ISSUE TITLE
Incorrect output from procrustesData

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#133]
The output from `procrustesData` is calculated incorrectly for `"ag_rmsd"`,  `"sr_rmsd"` and `"total_rmsd"`. The rmsd should be the rmsd of the positions (i.e the mean of the procrustes distances), not the rmsd of distances.

**Comment by shwilks** [comment]
I think that's what it currently does, i.e. takes the distance between the base antigen coordinate and the coordinate in the procrustes transformed version, then does the rmsd on those, or am I missing something?

**Comment by shwilks** [comment]
I think I still don't quite follow, could you write some example code that describes your alternative approach?  I think the rmsd calculated currently is the same as what is being minimised by the procrustes but perhaps I am missing something.

**Comment by drserajames** [comment]
Sorry!
