### ISSUE TITLE
`titerTableFlat` function not found

### ISSUE THREAD

**Issue by bamueh** [acorg/Racmacs#135]
I'm getting this error when trying to use the `titerTableFlat` function:

```
> titerTableFlat(m)
Error in titerTableFlat(m) : could not find function "titerTableFlat"
```

**Comment by bamueh** [comment]
Thanks a lot, Sarah!

**Comment by shwilks** [comment]
This is a bit of a backend function which I would imagine is very rarely used and likely to be confusing to most people so I'm not keen to export it, but happy to hear arguments otherwise.  You can still access unexported functions using the `:::` syntax, i.e. `Racmacs:::titerTableFlat()`
