### ISSUE TITLE
Racmacs install

### ISSUE THREAD

**Issue by Nicolaaht** [acorg/Racmacs#149]
I'm trying to re-install Racmacs. Gcc and Makevars updated

devtools::install_github("acorg/Racmacs")
Downloading GitHub repo acorg/Racmacs@HEAD
Error: Failed to install 'Racmacs' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
> pkgbuild::check_build_tools(debug = TRUE)
Trying to compile a simple C file
Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
gcc-13.1.0 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -O3 -c foo.c -o foo.o
/bin/sh: gcc-13.1.0: command not found
make: *** [foo.o] Error 127
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

Thoughts?

Thanks, Nic

**Comment by shwilks** [comment]
Sounds like maybe you need to fix your compiler toolchain.  There are some updated instructions on it you can try following here and see if it fixes it: https://shwilks.github.io/Racmacs/index.html

**Comment by Nicolaaht** [comment]
I think its still invoking clang version

(base) nicolalewis@Nicolas-MBP-2 .R % open Makevars
(base) nicolalewis@Nicolas-MBP-2 .R % gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(base) nicolalewis@Nicolas-MBP-2 .R %

**Comment by shwilks** [comment]
What does your current ~/.R/Makevars file look like?

**Comment by Nicolaaht** [comment]
I'm just changing the version to align with the fxcoudert ....

CC=gcc-12.2.0
CXX=/usr/local/bin/g++-12.2.0
CXX1X=/usr/local/bin/g++-12.2.0
CXX13.1.0=/usr/local/bin/g++-12.2.0
SHLIB_CXXLD=/usr/local/bin/g++-12.2.0
FC=/usr/local/bin/gfortran-12.2.0
F77=/usr/local/bin/gfortran-12.2.0
MAKE=make -j8
CFLAGS = -O3
CXXFLAGS = -O3

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

**Comment by shwilks** [comment]
You need to match the paths to the compilers that come with the gfortran version for me (on an M2 Mac) it ends up being:

```
CC=/usr/local/gfortran/bin/gcc
CXX=/usr/local/gfortran/bin/g++
CXX1X=/usr/local/gfortran/bin/g++
CXX11=/usr/local/gfortran/bin/g++
SHLIB_CXXLD=/usr/local/gfortran/bin/g++
FC=/usr/local/gfortran/bin/gfortran
F77=/usr/local/gfortran/bin/gfortran
MAKE=make -j8

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp
```

But I needed to find the right installer that gave me all these executables in /usr/local/gfortran/bin/

**Comment by Nicolaaht** [comment]
Is the next step to delete my Makevars and start again. I'm on an intel, Monterey 12.6.2

**Comment by Nicolaaht** [comment]
Last login: Tue Jun  6 11:09:12 on ttys000
(base) nicolalewis@Nicolas-MBP-2 ~ % which gfortran | xargs ls -l
lrwxr-xr-x  1 root  admin  32  6 Jun 12:45 /usr/local/bin/gfortran -> /usr/local/gfortran/bin/gfortran
(base) nicolalewis@Nicolas-MBP-2 ~ %

**Comment by shwilks** [comment]
Ok, it looks like it should work if you copy and paste my Makevars file instead.  Although you may want to double check that all the other executables in it like /usr/local/gfortran/bin/gcc also exist in that location on your system

**Comment by Nicolaaht** [comment]
All good. Thanks Sam.
________________________________

**Comment by Nicolaaht** [comment]
One query: what's the number next to the map stress? - bottom left of viewer window?

BW
Nicola
________________________________

**Comment by shwilks** [comment]
It's a calculation of the stress per titer to try and make map stress a bit more comparable between maps

**Comment by Nicolaaht** [comment]
Very helpful. So I don't need to try calculating this myself after all this time 😉
________________________________
