### ISSUE TITLE
install errors:  fatal error: sys/cdefs.h: No such file or directory

### ISSUE THREAD

**Issue by judyssister** [acorg/Racmacs#150]
Dear author, 

I am faced with a kind of installation problem. 
1. I have already installed the gcc (version 13) by "brew install gcc".
2. I updated the Makevars in  ~/.R/Makevars by: 
CXX=/usr/local/bin/g++-13
CXX1X=/usr/local/bin/g++-13
CXX11=/usr/local/bin/g++-13
SHLIB_CXXLD=/usr/local/bin/g++-13
FC=/usr/local/bin/gfortran-13
F77=/usr/local/bin/gfortran-13
MAKE=make -j8

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

3. I installed the Racmacs package using "devtools::install_github("acorg/Racmacs")" and I also tried install the package in local by "install.packages("Racmacs-1.1.4.tar.gz", repos = NULL)", but seem errors pop up.

> devtools::install_github("acorg/Racmacs")
Downloading GitHub repo acorg/Racmacs@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/7m/nx1sg16s6ysfgc092znjn0sc0000gn/T/RtmphZWROG/remotes54567f7ba560/acorg-Racmacs-9ca81ad/DESCRIPTION’ ...
─  preparing ‘Racmacs’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘Racmacs_1.1.35.tar.gz’
   
> installing *source* package ‘Racmacs’ ...
** using staged installation
** libs
>/usr/local/bin/g++-13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DSTRICT_R_HEADERS -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppEnsmallen/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rapidjsonr/include' -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c Racmacs_wrappers.cpp -o Racmacs_wrappers.o
In file included from /usr/local/Cellar/gcc/13.1.0/include/c++/13/cmath:47,
                 from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100,
                 from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include/Rcpp/r/headers.h:62,
                 from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include/RcppCommon.h:30,
                 from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include/RcppArmadillo/interface/RcppArmadilloForward.h:25,
                 from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include/RcppArmadillo.h:29,
                 from Racmacs_wrappers.cpp:2:
* /usr/local/Cellar/gcc/13.1.0/lib/gcc/current/gcc/x86_64-apple-darwin22/13/include-fixed/math.h:45:10: fatal error: sys/cdefs.h: No such file or directory
   45 | #include <sys/cdefs.h>
      |          ^~~~~~~~~~~~~_
compilation terminated.
make: *** [Racmacs_wrappers.o] Error 1
ERROR: compilation failed for package ‘Racmacs’
removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Racmacs’**
Warning message:
In i.p(...) :
>installation of package ‘/var/folders/7m/nx1sg16s6ysfgc092znjn0sc0000gn/T//RtmphZWROG/file545655e34178/Racmacs_1.1.35.tar.gz’ had non-zero exit status

Thank you very much and looking forward to hearing form you.

Cheers,
Jing

**Comment by shwilks** [comment]
Dear Jing,

Sorry to hear you're having installation problems, I recommend trying some alternative updated instructions described here and see if it fixes your compilation issues: https://shwilks.github.io/Racmacs/index.html

Best,
Sam

**Comment by judyssister** [comment]
Thanks a lot, Sam:) 

I install the [gfortran-12.2-universal.pkg](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg) and [gfortran-Intel-12.1-Monterey.dmg](https://github.com/fxcoudert/gfortran-for-macOS/releases/download/12.1-monterey/gfortran-Intel-12.1-Monterey.dmg). 

When I run  **which gfortran | xargs ls -l**, the screen prints:
.R % which gfortran | xargs ls -l
lrwxr-xr-x  1 root  admin  32  8 21 11:19 /usr/local/bin/gfortran -> /usr/local/gfortran/bin/gfortran

I checked files in **/usr/local/gfortran/bin/**:
 cd /usr/local/gfortran/bin 
yangjing@yangjingdeiMac bin % ls
cpp		gcc-ranlib	gnat		gnatlink	lto-dump
g++		gcov		gnatbind	gnatls
gcc		gcov-dump	gnatchop	gnatmake
gcc-ar		gcov-tool	gnatclean	gnatname
gcc-nm		gfortran	gnatkr		gnatprep

Then I updated the .R/Makevars as:
CC=/usr/local/gfortran/bin/gcc
CXX=/usr/local/gfortran/bin/g++
CXX1X=/usr/local/gfortran/bin/g++
CXX11=/usr/local/gfortran/bin/g++
SHLIB_CXXLD=/usr/local/gfortran/bin/g++
FC=/usr/local/gfortran/bin/gfortran
F77=/usr/local/gfortran/bin/gfortran
MAKE=make -j8

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

Finally, I run **devtools::install_github("acorg/Racmacs")**:
devtools::install_github("acorg/Racmacs")
>Downloading GitHub repo acorg/Racmacs@HEAD
Error: Failed to install 'Racmacs' from GitHub:
Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

> pkgbuild::check_build_tools(debug = TRUE)
Trying to compile a simple C file
Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
using C compiler: ‘gcc (GCC) 12.1.0’
using SDK: ‘’
/usr/local/gfortran/bin/gcc -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c foo.c -o foo.o
<built-in>: error: unknown value ‘13.4.0’ of ‘-mmacosx-version-min’
make: *** [foo.o] Error 1
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

My R version is 4.3.1, macOS version is  Ventura 13.4.1 and CPU is intel core i9. 
Could you please let me know where am I wrong?

Thank you very much.
Jing

**Comment by judyssister** [comment]
Did the wrong information caused by the version of gfortran-Intel-12.1-Monterey.dmg? Since the gfortran 12.2 doesn't have a dmg version, so I used gfortran 12.1...

**Comment by shwilks** [comment]
what do you get if you run `/usr/local/gfortran/bin/gfortran --version`

**Comment by judyssister** [comment]
The screen prints:

 **/usr/local/gfortran/bin/gfortran --version**
GNU Fortran (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by judyssister** [comment]
I borrowed a laptop with a Windows operating system from my group. The  Racmacs package could be installed very smoothly. However, I spent more than 2 days installing the package on my laptop with mac os, but I failed. The solution sometimes is to switch to another laptop. Hahahahaha...

**Comment by drserajames** [comment]
Just to say that Racmacs is on CRAN now, so you should be able to install it easily on your laptop: [https://cran.r-project.org/package=Racmacs](https://cran.r-project.org/package=Racmacs)
