### ISSUE TITLE
runGUI() function doesn't work

### ISSUE THREAD

**Issue by Adindakok** [acorg/Racmacs#25]
When using the function runGUI(), the following error appears:

`Listening on http://127.0.0.1:3526`
`Warning: Error in UseMethod: no applicable method for 'as.json' applied to an object of class "NULL"`
 ` 98: as.json
  97: RacViewer
  96: func `

`[/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Racmacs/shinyapps/RacmacsGUI/server.R#79]`

`  83: origRenderFunc
  82: output$racViewer
   2: shiny::runApp
   1: runGUI`

**Comment by shwilks** [comment]
Should be fixed in the latest version
