### ISSUE TITLE
Racmacs Install issue

### ISSUE THREAD

**Issue by ldamodaran** [acorg/Racmacs#29]
Hi I am trying to install Racmacs on a new machine and I am receiving this error:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘Racmacs’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Racmacs’
Error: Failed to install 'Racmacs' from GitHub:
  (converted from warning) installation of package ‘/var/folders/ln/25rgxwtj6p91fk4rtpb85vrm0000gn/T//Rtmpla3ypR/file815d2ee1194d/Racmacs_1.0.14.tar.gz’ had non-zero exit status

I am using R version 4.0.0. I am also using mac O.S 10.15.3  Any help would be greatly appreciated!

**Comment by harper357** [comment]
Did you end up figuring this out?

From the error, it looks like you might be missing Rcpp. Do you have it installed? Can you confirm that [acmacs.r](https://github.com/acorg/acmacs.r) is working?

**Comment by ldamodaran** [comment]
Hi!
Unfortunately i could not get it to work, it looks like there is an issue for acamac.r as well when i call the library i get this:

Error: package or namespace load failed for ‘acmacs.r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so

I also tried to reinstall acmacs.r and this comes up:
Warning in install.packages :
  package ‘https://github.com/acorg/acmacs.r/releases/download/v4.6/acmacs.r_4.6_R_macOS-10.14.tgz’ is not available (for R version 4.0.0)


Any help is appreicated thanks!

**Comment by harper357** [comment]
If possible, you might want to use R 3.6 . I am not sure if Racmacs fully supports R 4.0 . @shwilks can you answer?

Did you follow the directions on the acmacs.r page to install the dependencies? That error makes it sound like you are missing the Rcpp library, did you install it? 

Could you please include what steps (what was the exact code) did you take to install acmacs.r ? I am not sure why you would get that error as I have that version installed on R 4.0.2.

**Comment by ldamodaran** [comment]
Yeah, I think I might have to end up doing that for now.
Yes i followed thsoe directions and the Rcpp library installed wihout any issues when i used this command:

install.packages(c("Rcpp", "devtools", "testthat", "roxygen2"))

and I used this command for acmacs.r : 

install.packages(Find(function(asset) { grepl("macOS", asset$name, fixed=TRUE) }, devtools:::github_GET("repos/acorg/acmacs.r/releases/latest")$assets)$browser_download_url)

**Comment by shwilks** [comment]
Thanks for the bug report, sorry I missed the original message, thanks Greg for helping out.  Have you tried the installation command listed in the Racmacs documentation? (https://acorg.github.io/Racmacs/index.html)

```r
# Mac
remotes::install_url("https://github.com/acorg/acmacs.r/releases/download/v4.6/acmacs.r_4.6_R_macOS-10.14.tgz", build = FALSE)
```

**Comment by ldamodaran** [comment]
No worries, I have tried the install and it seems to work fine but when i call the acmac.r package it fails to load, here is the command and output:

> remotes::install_url("https://github.com/acorg/acmacs.r/releases/download/v4.6/acmacs.r_4.6_R_macOS-10.14.tgz", build = FALSE)
Downloading package from url: https://github.com/acorg/acmacs.r/releases/download/v4.6/acmacs.r_4.6_R_macOS-10.14.tgz
* installing *binary* package ‘acmacs.r’ ...
* DONE (acmacs.r)


> library(acmacs.r)
Error: package or namespace load failed for ‘acmacs.r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so

**Comment by ldamodaran** [comment]
Hm i am getting this error:
library(Rcpp)
Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
In addition: Warning message:
package ‘Rcpp’ was built under R version 4.0.2 

I tried to install.package("Rcpp") and it seemed to install without any errors but still shows this after loading the library

**Comment by shwilks** [comment]
Sounds like you may need to remove Rcpp, restart R, and install Rcpp again

**Comment by ldamodaran** [comment]
Looks like the universe doesn't want this R package to work for me, here is what I got:

remove.packages("Rcpp")
Removing package from ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
(as ‘lib’ is unspecified)

Restarting R session...

> install.packages("Rcpp")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/Rcpp_1.0.5.tgz'
Content type 'application/x-gzip' length 3215939 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

The downloaded binary packages are in
	/var/folders/ln/25rgxwtj6p91fk4rtpb85vrm0000gn/T//RtmpHFUmlV/downloaded_packages

> library(Rcpp)
Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
In addition: Warning message:
package ‘Rcpp’ was built under R version 4.0.2

**Comment by shwilks** [comment]
Yes, that's unfortunate, I've occasionally had it that I had to go and delete the files associated with a certain package by hand, maybe that's something to try?  Otherwise I would say give it a google and see how other people have managed to fix similar problems maybe?  You could also try deleting the acmacs.r package as part of the process in case that is interfering somehow - I doubt it but perhaps worth a try.

**Comment by ldamodaran** [comment]
Hey guys, I wanted to let you know that I was able to get things to work again by just completely removing R and reinstalling. Hopefully, if anyone else gets the issue they can see this, I removed all the associated libraries and reinstalled R 4.0.2.  Thanks for the help and your time!
