### ISSUE TITLE
sequence viewer empty / error

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#35]
Hi,

I'm trying out exploring sequence data in Racmacs.
I have successfully loaded sequences onto the map (I can colour by sequence via the control panel), but pressing the sequence viewer button results in an empty sequence viewer.
The following error displaying in my terminal window:
"Uncaught TypeError: Cannot read property 'noneSelected' of undefined".

(This is regardless of me selecting one antigen/serum or keeping all selected)

**Comment by shwilks** [comment]
Hi, thanks a lot for the error report!  I see I can repeat that same problem, the latest update broke that feature, I'll fix it and let you know when the package has been updated.

**Comment by shwilks** [comment]
I think the update I just merged should fix this problem but let me know if you are still having some problems!
