### ISSUE TITLE
package or namespace load failed for‘acmacs.r in dyn.load(file, DLLpath = DLLpath, ...)

### ISSUE THREAD

**Issue by Spatial-R** [acorg/Racmacs#37]
Hello, thanks for your nice package.  
When i have installed the package using the following codes:

`remotes::install_local("/home/dell2/download/acmacs.r_5.1_R_x86_64-pc-linux-gnu.tar.gz",build = F)`

There is no error. However, when i used the ` library(acmacs.r)`, the error comes:

`error: package or namespace load failed for ‘acmacs.r’ in dyn.load(file, DLLpath = DLLpath, ...):
 fail to load the shared object‘/home/dell2/R/x86_64-pc-linux-gnu-library/4.0/acmacs.r/libs/acmacs.r.so’：:
  /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /home/dell2/R/x86_64-pc-linux-gnu-library/4.0/acmacs.r/libs/libacmacschart.so.2)`

My session information is as followed:

`R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C               LC_TIME=zh_CN.UTF-8       
 [4] LC_COLLATE=zh_CN.UTF-8     LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringi_1.5.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        ps_1.5.0          fansi_0.4.1       prettyunits_1.1.1 withr_2.3.0      
 [6] crayon_1.3.4      rprojroot_2.0.2   assertthat_0.2.1  R6_2.5.0          cli_2.2.0        
[11] remotes_2.2.0     rstudioapi_0.13   callr_3.5.1       tools_4.0.3       glue_1.4.2       
[16] compiler_4.0.3    processx_3.4.5    pkgbuild_1.1.0  `

**Comment by shwilks** [comment]
Thanks for the bug report, I'll forward your problem onto the acmacs.r maintainer to see if he can help.  I'm currently working on a new C++ backend for Racmacs that should allow you to build the package locally and avoid these problems in the future, hopefully it will be available in the next week or so, but ideally we can fix your acmacs.r installation problem in the meantime.

**Comment by skepner** [comment]
Hello,
We don't have old ubuntu linux around to make acmacs.r binaries for you. You may either try to build acmacs backend from sources yourself, it is not trivial but I can help you or upgrade linux to 20.04.
If you decide to build acmacs from sources, please write me to eu@antigenic-cartography.org and I give you instructions.
Eugene

**Comment by Spatial-R** [comment]
Hello, thanks for your kindly help on my question. Today, i have updated my computer from Ubuntu 18.04 to Ubuntu 20.04.  Now, i have successfully installed the Racmacs package.

**Comment by shwilks** [comment]
Closing this since we have now developed Racmacs to no longer use acmacs.r
