### ISSUE TITLE
Antigens or sera do not have enough titrations to establish their antigenic position

### ISSUE THREAD

**Issue by Spatial-R** [acorg/Racmacs#38]
Hello. Thanks for your nice help. 
Recently, i used the Racmacs package to calculate the antigenic distance, however, error comes when running the optimizeMap function: 

`Performing 1000 optimization runs...done.    
Moving trapped points in the lowest stress optimization...    
Error in map$chart$projections[[optimization_number]]$relax("cg", FALSE) :     
  invalid_data: alglib error: MinCGCreate: X contains infinite or NaN values!`

Is there any solution to this problem? Thanks again and look forward to hearing from you.

My data is [here](https://github.com/Spatial-R/Data-visualization-in-public-health/blob/master/title_table.csv)

**Comment by shwilks** [comment]
Hi there, thanks a lot for the bug report and sending the data that generated it, I'll take a look and see if I can reproduce the error.  It may be that certain antigens or sera do not have enough titrations to establish their antigenic position, in which case we can update the error message to be something more useful and informative.

**Comment by Spatial-R** [comment]
Yes. I have changed the issue title. I think it is useful to check the dataset and remove the special antigens or sera that do not have enough titrations with certain criterion, before running the optimizeMap function.

**Comment by harper357** [comment]
@shwilks Does Racmacs not optimize an antigen's position if it doesn't have enough titrations? I think I was having the same issue, and Derek suggested that it should still be optimizing them, or at least that is what LispMDS did.

**Comment by shwilks** [comment]
Hi @harper357, thanks for reminding me about this issue, in the current version of Racmacs referred to in the original issue, it will do whatever is implemented in acmacs.r, I'm not sure what that is, we'd have to check with @skepner.  But given we are re-writing the backend for Racmacs and removing acmacs.r we can specify whatever behaviour we would like in the new version.

I was thinking that we would not optimise points with too few titrations to position them, i.e. at least 3 titrations in 2d, treating them as disconnected points with NaN coordinates, but perhaps this is too harsh? It has certainly come up before as something people want. I guess it is ok to have although how far would we allow, would we "optimise" points with only 1 titer in 2d maps? presumably those with 0 titers we have to class as disconnected and give a warning?

**Comment by harper357** [comment]
I would think it should at least give people a warning about those points. Longer-term, and this might already be the plan, it could be worth it to have some pre-optimization table checks with the option to run without it. That should probably go in a separate issue, though.

I agree it isn't clear where the cutoff should be, but I think in the case of 2D maps, only having 2 points should be ok as there are still only a finite number of positions. A warning would allow the user to remove it if they wanted to, and when they look at procrustes of the top optimizations, it would be clear that the antigen can move. The problem with just assigning their location (NaN, NaN) is that the trapped points and procrustes functions seem to fail.

**Comment by shwilks** [comment]
Yeah, all good ideas and points.  Perhaps you would be up for doing some work on writing some tests to check cases like this in the new version Greg and implementing such table checks?  I'm going to try and release the new version on a separate branch tomorrow.

**Comment by harper357** [comment]
Yeah, I should be able to do that.

**Comment by askarlupka** [comment]
Related to this thread, I know that Racmacs will give a warning message that sera or antigens can not be positioned: "The following antigens have do not have enough titrations to position in 2 dimensions. Coordinates were still optimized but positions will be unreliable: [List of strain/sera names] "

However, is there a way to extract those listed strains/sera to remove them from the next optimization? I'm trying to come up with something a little more elegant than copy and pasting the warning message, but I can't figure out how to pull those names.

**Comment by shwilks** [comment]
Good question - the list of strains that appear in these messages are simply determined by the number of measurable titers they have compared to the number of dimensions there are.  I think it's currently set up so that strains with < n + 1 measurable titers get this warning, where n is the number of dimensions.  So I think the easiest way would be for you to run this check and find the problematic strains that way if that makes sense?
