### ISSUE TITLE
Install instructions differ between Github and website

### ISSUE THREAD

**Issue by harper357** [acorg/Racmacs#39]
The GitHub README and the acorg.github.io/Racmacs landing page have differing install instructions. 

Looks like there is a README file and an index file. Any reason you aren't just using the README as the landing page?

**Comment by shwilks** [comment]
The README file, gets shown on github of course, the index file get's rendered by pkgdown into the index page of the docs website acorg.github.io/Racmacs

We may indeed want slightly different things for github and the docs homepage, but yeah, you are right, not different installation instructions, this should be fixed!

**Comment by harper357** [comment]
I think I mentioned it in my PR, but if their is no index file, pkgdown just renders the README as the index, so unless there is a current difference you want, the index file should probably just be removed to keep things simple.

**Comment by shwilks** [comment]
yeah, although I wonder if we do indeed want differences between a more code-oriented github readme intro and user-oriented index page?

**Comment by shwilks** [comment]
Closing since we just have a single readme for now as you had suggested
