### ISSUE TITLE
make.acmap does not respect set.seed

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#4]
@belinda-clark noticed that repeats of make.acmap do no give the same result after using set.seed. For example:

```
library(Racmacs)

set.seed(1)
tab <- matrix(10*2^sample(0:7, 100, replace=T), ncol=10)

map <- NULL
for (i in 1:16){
  set.seed(1)
  map[[i]] <- make.acmap(table=tab, number_of_optimizations=1, remove_trapped_points="none")
}
```
![same-data-different-map](https://user-images.githubusercontent.com/18366410/68390428-2f937280-015d-11ea-92ae-7e9d424fc8b8.png)

These all have the same stress so these maps could just be rotated.

I wonder if maps could be generated like this, but with different stresses, and then it would mean analyses were not reproducible.

**Comment by shwilks** [comment]
Eu tells me it is very difficult to allow us to set a seed to acmacs.r.  This might be something we need to push a bit on if we really want it.

**Comment by shwilks** [comment]
This from @skepner on this topic on 14th May 2019:

> Will add it to may todo list. It is not easy, may require a lot of debugging. Ability to seed parallel optimisation slows down everything, i.e. I have to fork acmacs and maintain two versions: one without seeding which I need for WHO CC stuff and another with seeding which will be slower. 
> 
> Resume: I can add seed argument to $relax. I will not add seed argument to other functions unless Derek explicitly asks me to do it.
> 
> BTW, adding to todo list means implementing for v4 which is not going to be done soon.
> 
> Eu

**Comment by shwilks** [comment]
Re-reading this it sounds to me like it adding it to $relax and not bothering with $relax_many may be the way to go. If we set the seed we can simply call $relax multiple times rather than running in parallel.

**Comment by skepner** [comment]
seeded optimization implemented in acmacs.r v4.0
also, if you think that layout randomization implemented in acmacs.r is not good, you may use your own (with fixed or inferred from random device seed) using chart$new_projection_with_layout

**Comment by skepner** [comment]
Note acmacs.r implementation cannot respect set.seed and any other R options, it does not access R environment (and will never do)

**Comment by drserajames** [comment]
Thanks, Eu.
