### ISSUE TITLE
NaNs in dimensionTestMap

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#42]
Hi,

I've got a dataset for which dimensionTestMap (run in Racmacs v1.0.17) results in a table full of NaN's.
Please would you be able to advise on interpretation, or what could have gone wrong?
(It looks to me like an issue to do with the relatively large number of *s in this dataset)

I've tried (1) limiting the test to 2D & 3D [of most interest], and (2) removing sera with few datapoints/a lot of * - but the results remain the same.
For the same data, 2D and 3D maps are made and optimised without obvious problems.

Thank you!

Carlijn

**Comment by shwilks** [comment]
Thanks for the error report, it sounds like you're right about it probably being to do with a situation where there are lots of non-detectable titers, I would guess that when, as part of excluding further data during cross-validation, too many remaining detectable titers get set to * for a point, it ends up with NaN coordinates and these NaNs are perhaps being propagated through the calculations that lead to the summary table you get as output.

I've been working on a new version of Racmacs with a new C++ backend for things like map optimization and dimension testing.  It's currently in beta but it would be interesting to know whether you still have the same problems in this version. The new beta is currently on my own fork so you can install it with

`devtools::install_github("shwilks/Racmacs")`

There are some specific installation instructions relating to building the new version from source at https://shwilks.github.io/Racmacs or if you are running on a mac we could try sharing a pre-built version if you have trouble compiling it.

If there is a minimal dataset you could share that's having these problems that would be really helpful too.

Best,
Sam
