### ISSUE TITLE
Racmacs install build fail

### ISSUE THREAD

**Issue by Nicolaaht** [acorg/Racmacs#44]
Hi all
Tried to update Racmacs but build failed:
I had updated R version, devtools, acmacs.r
Thoughts? Thanks!

> devtools::install_github("acorg/Racmacs")
Downloading GitHub repo acorg/Racmacs@HEAD
✓  checking for file ‘/private/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T/Rtmp165zLz/remotes3d15814e896/acorg-Racmacs-d22a83b/DESCRIPTION’ ...
─  preparing ‘Racmacs’: (593ms)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Racmacs_1.0.17.tar.gz’
   
ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Racmacs’
Error: Failed to install 'Racmacs' from GitHub:
  (converted from warning) installation of package ‘/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T//Rtmp165zLz/file3d1526d514f6/Racmacs_1.0.17.tar.gz’ had non-zero exit status

**Comment by shwilks** [comment]
Hmm, hard to say, what's your operating system?  Also are you able to compile and install the new beta version with `devtools::install_github("acorg/Racmacs", ref = "v1.1")`

**Comment by shwilks** [comment]
Removing any previous installation, and restarting your R session is also another good thing to try

**Comment by Nicolaaht** [comment]
I had tried restarting R session, and also removing previous. 
library(Racmacs)
Error in library(Racmacs) : there is no package called ‘Racmacs’
> devtools::install_github("acorg/Racmacs")
Downloading GitHub repo acorg/Racmacs@HEAD
✓  checking for file ‘/private/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T/RtmpcGPnqE/remotes450e59474e66/acorg-Racmacs-d22a83b/DESCRIPTION’ ...
─  preparing ‘Racmacs’: (608ms)
✓  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Racmacs_1.0.17.tar.gz’
   
ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Racmacs’
Error: Failed to install 'Racmacs' from GitHub:
  (converted from warning) installation of package ‘/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T//RtmpcGPnqE/file450e28e64026/Racmacs_1.0.17.tar.gz’ had non-zero exit status
> 

However - I'm still on Catalina 10.15.17 not Big Sur? Usually I wait before updating the OS, to allow all the glitches to be fixed;)

I'll try the beta install now

**Comment by Nicolaaht** [comment]
> devtools::install_github("acorg/Racmacs", ref = "v1.1")
Downloading GitHub repo acorg/Racmacs@v1.1
Downloading GitHub repo shwilks/rmarchingcubes@HEAD
✓  checking for file ‘/private/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T/RtmpcGPnqE/remotes450e35bc0c8a/shwilks-rmarchingcubes-407806e/DESCRIPTION’ ...
─  preparing ‘rmarchingcubes’:
✓  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rmarchingcubes_0.1.1.tar.gz’
   
* installing *source* package ‘rmarchingcubes’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c MarchingCubes.cpp -o MarchingCubes.o
In file included from MarchingCubes.cpp:21:
In file included from ./MarchingCubes.h:17:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./rmarchingcubes_types.h:2:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c wrappers.cpp -o wrappers.o
In file included from wrappers.cpp:2:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rmarchingcubes.so MarchingCubes.o RcppExports.o wrappers.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [rmarchingcubes.so] Error 1
ERROR: compilation failed for package ‘rmarchingcubes’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarchingcubes’
Error: Failed to install 'Racmacs' from GitHub:
  Failed to install 'rmarchingcubes' from GitHub:
  (converted from warning) installation of package ‘/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T//RtmpcGPnqE/file450e4cdb5395/rmarchingcubes_0.1.1.tar.gz’ had non-zero exit status


Is this an R version incompatibility?

**Comment by shwilks** [comment]
Thanks for the update, the problems compiling the new version look like a compiler incompatibility rather than anything to do with your os.  By default mac uses the clang++ compiler, which seems to be having problems, I would recommend compiling it using g++, not least because then the code will compile in parallel and run much faster.  There are some instructions here as to how to change your default compiler:

https://shwilks.github.io/Racmacs/index.html#building-racmacs-to-run-code-in-parallel

I would post a pre-compiled version for you here to save you the hassle but unfortunately I'm on BigSur now so I doubt it would work for your system.  Let us know how you get on.

**Comment by Nicolaaht** [comment]
Thanks, Sam - I'll give the compiler a go. Otherwise I can update to Big Sur and we can try the pre-compiled version... I was just sitting on the fence to allow enough time after initial release for the bugs to be resolved....

**Comment by Nicolaaht** [comment]
Just in case it helps anyone else: follow above instructions on changing compiler. 
I put the Makevars in ~/.R/Makevars then used nano to add below to Makevars

CXX=/usr/local/bin/g++-10
CXX1X=/usr/local/bin/g++-10
CXX11=/usr/local/bin/g++-10
SHLIB_CXXLD=/usr/local/bin/g++-10
FC=/usr/local/bin/gfortran-10
F77=/usr/local/bin/gfortran-10
MAKE=make -j8

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

I thought we had resolved but got the below which I fixed by >Try removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Racmacs’

> devtools::install_github("acorg/Racmacs", ref = "v1.1")
Downloading GitHub repo acorg/Racmacs@v1.1
Downloading GitHub repo shwilks/rmarchingcubes@HEAD
✓  checking for file ‘/private/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T/RtmpD6VIXv/remotes1af53ca40a5/shwilks-rmarchingcubes-407806e/DESCRIPTION’ ...
─  preparing ‘rmarchingcubes’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rmarchingcubes_0.1.1.tar.gz’
   
* installing *source* package ‘rmarchingcubes’ ...
** using staged installation
** libs
/usr/local/bin/g++-10 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include  -fopenmp  -fPIC  -Wall -g -O2  -c MarchingCubes.cpp -o MarchingCubes.o
/usr/local/bin/g++-10 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include  -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
/usr/local/bin/g++-10 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include  -fopenmp  -fPIC  -Wall -g -O2  -c wrappers.cpp -o wrappers.o
/usr/local/bin/g++-10 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rmarchingcubes.so MarchingCubes.o RcppExports.o wrappers.o -fopenmp -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-rmarchingcubes/00new/rmarchingcubes/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rmarchingcubes)
Installing 3 packages: rapidjsonr, RcppEnsmallen, roptim
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rapidjsonr_1.2.0.tgz'
Content type 'application/x-gzip' length 130409 bytes (127 KB)
==================================================
downloaded 127 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/RcppEnsmallen_0.2.16.1.1.tgz'
Content type 'application/x-gzip' length 649887 bytes (634 KB)
==================================================
downloaded 634 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/roptim_0.1.5.tgz'
Content type 'application/x-gzip' length 815349 bytes (796 KB)
==================================================
downloaded 796 KB


The downloaded binary packages are in
	/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T//RtmpD6VIXv/downloaded_packages
Skipping install of 'rmarchingcubes' from a github remote, the SHA1 (407806e8) has not changed since last install.
  Use `force = TRUE` to force installation
✓  checking for file ‘/private/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T/RtmpD6VIXv/remotes1af547746242/acorg-Racmacs-f4cf5c7/DESCRIPTION’ ...
─  preparing ‘Racmacs’: (833ms)
✓  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Racmacs_1.1.3.tar.gz’
   
ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Racmacs’
Error: Failed to install 'Racmacs' from GitHub:
  (converted from warning) installation of package ‘/var/folders/c3/03v2vmfj7j591xh7sxt2639w0000gn/T//RtmpD6VIXv/file1af51c3e3344/Racmacs_1.1.3.tar.gz’ had non-zero exit status
