### ISSUE TITLE
Minimal/no output for optimizeMap

### ISSUE THREAD

**Issue by harper357** [acorg/Racmacs#45]
First off, I really like and am glad to see the progress bar and time. I think they are great UX. 

However, there are times when I am running code where it would be great to have it run silently or with minimal output (ex: it is part of a longer pipeline, or I am writing the output to file). Since the progress bar is done with repeated writes to the console, I wonder if there is a way to not show it?

Code run:
```
> titertable <- read.titerTable("./tests/testdata/titer_tables/titer_table1.csv")
> map1 <- optimizeMap(
+ map = map,
+ number_of_dimensions = 2,
+ number_of_optimizations = 1,
+ minimum_column_basis = "none",
+ verbose = FALSE
+ )
Performing 1 optimizations
=============================================================================================
Optimization runs complete
```
Expectation:
```
> map1 <- optimizeMap(
+ map = map,
+ number_of_dimensions = 2,
+ number_of_optimizations = 1,
+ minimum_column_basis = "none",
+ verbose = FALSE
+ )
Performing 1 optimizations
Optimization runs complete & took 0.03 secs
```

I know there is ```invisible()``` that would completely silence the output, but I have no idea if it is best practice in R to just use that, or if there should be a built-in option.

If others are interested, I am happy to try making a pull request. If this would just be bloat, I will just use ```invisible()```.

**Comment by shwilks** [comment]
Take a look at 

```
map <- optimizeMap(
 map = map,
 number_of_dimensions = 2,
 number_of_optimizations = 100,
 minimum_column_basis = "none",
 options = list(
  report_progress = FALSE
 )
)
```

I think this might be what you're talking about?

**Comment by harper357** [comment]
Well dang, consider this closed.
