### ISSUE TITLE
Is there a way to make this run in M1 chip mac os?

### ISSUE THREAD

**Issue by 7rewcho** [acorg/Racmacs#51]
Installing was not a issue. 

However, when I try to run optimization function , it crashes.

**Comment by shwilks** [comment]
Hi there, sorry to hear about the problems, I'm guessing you're using version v1.0.16?  If so you might like to try the new version that you can build yourself from the source code with 

```
devtools::install_github("acorg/Racmacs", "v1.1")
```

You may need to change your default compiler from clang to gcc, there are some instructions here https://shwilks.github.io/Racmacs/index.html

Let me know how you get on!
