### ISSUE TITLE
Thanks Sam. Forgot to mention that I updated my mac to Big Sur so yes I have gcc but the defaults may have been altered. I reinstalled gcc, made the Makevars file in .R and added those lines, but I had to change the versions to 11 instead of 10.  And it works now.

### ISSUE THREAD

**Issue by Nicolaaht** [acorg/Racmacs#57]
Thanks Sam. Forgot to mention that I updated my mac to Big Sur so yes I have gcc but the defaults may have been altered. I reinstalled gcc, made the Makevars file in .R and added those lines, but I had to change the versions to 11 instead of 10.  And it works now.

_Originally posted by @dven42 in https://github.com/acorg/Racmacs/issues/56#issuecomment-840818343_

**Comment by Nicolaaht** [comment]
Reopening this:

I am now installing on BigSur, new machine. I had to re-install gcc via Homebrew. I too had to change gcc version to 11 in ~/.R/Makevars file.

CXX=/usr/local/bin/g++-11    
CXX1X=/usr/local/bin/g++-11    
CXX11=/usr/local/bin/g++-11    
SHLIB_CXXLD=/usr/local/bin/g++-11    
FC=/usr/local/bin/gfortran-11    
F77=/usr/local/bin/gfortran-11    
MAKE=make -j8

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

**Comment by shwilks** [comment]
Thanks, good to know, I’ll update the readme
