### ISSUE TITLE
MergeMap issue with acmap object recognition

### ISSUE THREAD

**Issue by Nicolaaht** [acorg/Racmacs#58]
Hi Sam and all

has anyone else found that the mergeMap function issues the following error:
Error: Input must be an acmap object

Despite trying to merge already optimised acmap objects made with make.acmap as map1 and map2, Also tried method = "table" or method = "incremental-merge"

Racmacs v 1.1.4 on BigSur with Rv 4.0.5

**Comment by shwilks** [comment]
Hi there, mergeMap takes a list of maps, i.e. `mergeMap(list(map1, map2))` maybe that is that problem?  I think the error message could be more helpful though.

**Comment by Nicolaaht** [comment]
on my new (unnetworked) machine so typing the error but:

merge <- mergeMaps(list(map2, map3, method = "table")) and all perms and combos = same error

The acmap objects in the environment look correct. List of acoptimizations etc

I've also tried .ace and full path to .ace but as you say, difficult to figure out what it is 'objecting' to

Anything obvious?

**Comment by shwilks** [comment]
`mergeMaps(list(map2, map3), method = "table")`

**Comment by Nicolaaht** [comment]
Thanks! sorted....now going to try incremental....

**Comment by shwilks** [comment]
no worries, I've updated the error message to be more helpful in future

**Comment by Nicolaaht** [comment]
Its really quick optimising btw ;) I'll try it on some massive swine tables in 3D and see how we go

**Comment by shwilks** [comment]
yeah, would be interested to hear how it goes!  If it's getting really big I might have to change how the 3d points are rendered a bit beyond a certain number of points but see how you get on.
