### ISSUE TITLE
Not able to install R package

### ISSUE THREAD

**Issue by srinithyamantrananda** [acorg/Racmacs#62]
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
ERROR: dependency 'rmarchingcubes' is not available for package 'Racmacs'

**Comment by shwilks** [comment]
Hi there, thanks getting in touch.  Could you give some details of your OS and R version you are using?  Re the specific issue here it would be worth working out if you can get the rmarching cubes package installed with 

```
devtools::install_github("shwilks/rmarchingcubes")
```

**Comment by srinithyamantrananda** [comment]
Hey Sam,
I'm using windows 10 with R 4.04.

Janarthan

**Comment by shwilks** [comment]
Thanks, and what output do you get if you try and install `rmarchingcubes` with the command above?

**Comment by srinithyamantrananda** [comment]
Hey Sam,

I am having a problem installing the rmarchingcubes package as well using
the devtools::install_github("shwilks/rmarchingcubes") command.

Here is the response I got from Rstudio:

> devtools::install_github("shwilks/rmarchingcubes")
Downloading GitHub repo shwilks/rmarchingcubes@HEAD
√  checking for file
'C:\Users\xramja\AppData\Local\Temp\Rtmp00fAn4\remotes4f6073df87c\shwilks-rmarchingcubes-8f522f2/DESCRIPTION'
...
-  preparing 'rmarchingcubes':
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'rmarchingcubes_0.1.2.tar.gz'

Installing package into ‘\\
home.gu.gu.se/home-XR$/xramja/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
'\\home.gu.gu.se\home-XR$\xramja\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'rmarchingcubes' ...
** using staged installation
** libs
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11
-I"C:/PROGRA~1/R/R-40~1.4/include" -DNDEBUG  -I'\\
home.gu.gu.se/home-XRxramja/Documents/R/win-library/4.0/Rcpp/include' -I'\\
home.gu.gu.se/home-XRxramja/Documents/R/win-library/4.0/RcppArmadillo/include'
    -fopenmp    -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c
MarchingCubes.cpp -o MarchingCubes.o
MarchingCubes.cpp:21:10: fatal error: RcppArmadillo.h: No such file or
directory
 #include <RcppArmadillo.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.4/etc/x64/Makeconf:229: MarchingCubes.o]
Error 1
ERROR: compilation failed for package 'rmarchingcubes'
* removing '\\
home.gu.gu.se/home-XR$/xramja/Documents/R/win-library/4.0/rmarchingcubes'
Warning message:
In i.p(...) :
  installation of package
‘C:/Users/xramja/AppData/Local/Temp/Rtmp00fAn4/file4f602a7b58b0/rmarchingcubes_0.1.2.tar.gz’
had non-zero exit status


Regards
Janarthan

**Comment by shwilks** [comment]
Hmm.. strange, that package seems to build ok and run on windows in the tests.  I wonder if the problem is that you haven't installed the dependency `RcppArmadillo` and for some reason this is not being installed automatically as part of the process.  You could try installing it explicitly with `install.packages("RcppArmadillo")` and trying again.

I've now submitted that particular package to CRAN so hopefully that should make installation easier if it is accepted.  In the meantime if the above still doesn't work for you I would suggest trying to install from the pre-compiled zip file you can download from here https://win-builder.r-project.org/odyvur2p2725/ and see if that installs ok?

**Comment by srinithyamantrananda** [comment]
Hey Sam,
I already had the RcppAmadillo package installed. I managed to install the
rmarchingcubes package successfully via the link you sent me. However, I am
still not able to install the Racmacs package. This is the output I get
when I try installing Racmacs:

=============================================================================================================================================
> devtools::install_github("acorg/Racmacs")
Downloading GitHub repo acorg/Racmacs@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All
2: CRAN packages only
3: None
4: rmarching... (0.1.2 -> 8f522f240...) [GitHub]
5: cachem       (1.0.4 -> 1.0.5       ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
√  checking for file
'C:\Users\xramja\AppData\Local\Temp\Rtmp00fAn4\remotes4f605c564b60\acorg-Racmacs-efb171a/DESCRIPTION'
(818ms)
-  preparing 'Racmacs': (7.9s)
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
(1.1s)
-  checking for empty or unneeded directories (384ms)
-  building 'Racmacs_1.1.9.tar.gz'

Installing package into ‘\\
home.gu.gu.se/home-XR$/xramja/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
'\\home.gu.gu.se\home-XR$\xramja\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'Racmacs' ...
** using staged installation
** libs
/mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.4/include" -DNDEBUG
-DSTRICT_R_HEADERS -I'\\
home.gu.gu.se/home-XRxramja/Documents/R/win-library/4.0/Rcpp/include' -I'\\
home.gu.gu.se/home-XRxramja/Documents/R/win-library/4.0/RcppArmadillo/include'
-I'\\
home.gu.gu.se/home-XRxramja/Documents/R/win-library/4.0/RcppProgress/include'
-I'\\
home.gu.gu.se/home-XRxramja/Documents/R/win-library/4.0/RcppEnsmallen/include'
-I'\\
home.gu.gu.se/home-XRxramja/Documents/R/win-library/4.0/rapidjsonr/include'
    -fopenmp   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c
Racmacs_types.cpp -o Racmacs_types.o
Racmacs_types.cpp:2:10: fatal error: RcppArmadillo.h: No such file or
directory
 #include <RcppArmadillo.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.4/etc/x64/Makeconf:229: Racmacs_types.o]
Error 1
ERROR: compilation failed for package 'Racmacs'
* removing '\\
home.gu.gu.se/home-XR$/xramja/Documents/R/win-library/4.0/Racmacs'
Warning message:
In i.p(...) :
  installation of package
‘C:/Users/xramja/AppData/Local/Temp/Rtmp00fAn4/file4f6046b12d1a/Racmacs_1.1.9.tar.gz’
had non-zero exit status
============================================================================================================================================

Regards
Janarthan

**Comment by shwilks** [comment]
hmm, yeah it looks like a similar problem then, I'll run winbuilder on the package for you and send you a similar link I think to save you having to compile it

**Comment by srinithyamantrananda** [comment]
That will be very useful. Thank you very much for your support, I really
appreciate it!!

Regards
Janarthan

**Comment by srinithyamantrananda** [comment]
Greetings Sam
Do you have the compiled and compressed Racmacs package available?

Regards
Janarthan

**Comment by shwilks** [comment]
I've tried creating precompiled versions on a branch of my fork, see if it works for you to install it with the following:

```
remotes::install_url("https://github.com/shwilks/Racmacs/raw/gh-builds/R_v4/Racmacs_latest_x86_64-w64-mingw32.zip", build = FALSE)
```

Let me know if that works or not, it would be helpful to know, thanks!

**Comment by srinithyamantrananda** [comment]
Hey Sam,
Thank you for the update.  I tried installing this with the above command
in R, however it failed to install the package. This is the output I got

> remotes::install_url("
https://github.com/shwilks/Racmacs/raw/gh-builds/R_v4/Racmacs_latest_x86_64-w64-mingw32.zip",
build = FALSE)
Downloading package from url:
https://github.com/shwilks/Racmacs/raw/gh-builds/R_v4/Racmacs_latest_x86_64-w64-mingw32.zip
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All
2: CRAN packages only
3: None
4: colorspace (2.0-1  -> 2.0-2 ) [CRAN]
5: cli        (2.5.0  -> 3.0.0 ) [CRAN]
6: ks         (1.13.1 -> 1.13.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
Installing package into ‘\\
home.gu.gu.se/home-XR$/xramja/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *binary* package 'Racmacs' ...
Warning in system(paste("cp -R .", shQuote(instdir), "|| (", TAR, "cd - .|
(cd",  :
  'cp' not found
ERROR: installing binary package failed
* removing '\\
home.gu.gu.se/home-XR$/xramja/Documents/R/win-library/4.0/Racmacs'
Warning message:
In i.p(...) :
  installation of package
‘C:/Users/xramja/AppData/Local/Temp/Rtmp4acz9P/remotes1fe87ed357c4/Racmacs’
had non-zero exit status


Regards
Janarthan

**Comment by srinithyamantrananda** [comment]
I also tried downloading the package as .zip file and install it from a
local source. It still failed to install, and this is the output I got



install.packages("C:/Users/xramja/Downloads/Racmacs_latest_x86_64-w64-mingw32.zip",
repos = NULL, type = "win.binary")
Installing package into ‘\\
home.gu.gu.se/home-XR$/xramja/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open compressed file
'Racmacs_latest_x86_64-w64-mingw32/DESCRIPTION', probable reason 'No such
file or directory'
Error in install.packages : cannot open the connection



Regards
Janarthan

**Comment by shwilks** [comment]
hmm, yeah I'm getting the same problems, does it work with the package here:

```https://win-builder.r-project.org/Q58HK7CD8w2Z/Racmacs_1.1.11.zip```

**Comment by shwilks** [comment]
This seems to work for me if I run
```
install.packages("https://win-builder.r-project.org/Q58HK7CD8w2Z/Racmacs_1.1.11.zip", repos = NULL)
```

**Comment by srinithyamantrananda** [comment]
Hey Sam,
Thank you very much. I am glad to inform you that the R command above
worked well for me. I have now successfully installed the Racmacs package.
Have a great weekend!! :)

Regards
Janarthan

**Comment by shwilks** [comment]
Phew, thanks for persevering, have a good weekend too!
