### ISSUE TITLE
R studio Cloud

### ISSUE THREAD

**Issue by pmontine** [acorg/Racmacs#63]
I have problem with devtools::install_github("acorg/Racmacs") . I am using Rstudio cloud 

My error is ... 

devtools::install_github("acorg/Racemacs") Error: Failed to install 'unknown package' from GitHub:   HTTP error 404.   Not Found    Did you spell the repo owner (`acorg`) and repo name (`Racemacs`) correctly?   - If spelling is correct, check that you have the required permissions to access the repo. > devtools::install_github("acorg/Racmacs") Downloading GitHub repo acorg/Racmacs@HEAD ✓  checking for file ‘/tmp/RtmpJfqTCD/remotes49f3716ad0c/acorg-Racmacs-efb171a/DESCRIPTION’ ... ─  preparing ‘Racmacs’: ✓  checking DESCRIPTION meta-information ... ─  cleaning src ─  checking for LF line-endings in source and make files and shell scripts ─  checking for empty or unneeded directories ─  building ‘Racmacs_1.1.9.tar.gz’     Installing package into ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0’ (as ‘lib’ is unspecified) * installing *source* package ‘Racmacs’ ... ** using staged installation ** libs g++ -std=gnu++11 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG -DSTRICT_R_HEADERS -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include' -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/RcppArmadillo/include' -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/RcppProgress/include' -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/RcppEnsmallen/include' -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/rapidjsonr/include' -I/usr/local/include  -fopenmp -fpic  -g -O2  -c Racmacs_types.cpp -o Racmacs_types.o g++: fatal error: Killed signal terminated program cc1plus compilation terminated. make: *** [/opt/R/4.0.3/lib/R/etc/Makeconf:181: Racmacs_types.o] Error 1 ERROR: compilation failed for package ‘Racmacs’ * removing ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/Racmacs’ Warning message: In i.p(...) :   installation of package ‘/tmp/RtmpJfqTCD/file49f420c44fd/Racmacs_1.1.9.tar.gz’ had non-zero exit status
--
 
Not sure how to fix,

**Comment by shwilks** [comment]
Hi there, spelling is Racmacs, not Racemacs, hopefully that fixes things! :)

**Comment by pmontine** [comment]
> Hi there, spelling is Racmacs, not Racemacs, hopefully that fixes things! :)

So the spelling isn't the problem. I get this error message.

g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [/opt/R/4.0.3/lib/R/etc/Makeconf:181: Racmacs_types.o] Error 1
ERROR: compilation failed for package ‘Racmacs’
* removing ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/Racmacs’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp5VHNT6/fileed48d704f7/Racmacs_1.1.9.tar.gz’ had non-zero exit status
