### ISSUE TITLE
more point shapes?

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#66]
Hi Sam,

To make antigenic maps more colour-blind-accessible, I'd like to use different point shapes rather than only rely on colour coding.
I found in your code that, other than the default "CIRCLE" and "BOX",  "TRIANGLE" and "EGG" are the only additional point shap options.

Would you consider adding more point shapes (to be set directly with pch names or numbers?)

Thank you!

Carlijn

**Comment by shwilks** [comment]
Yes, you're correct about the currently supported shapes, good to know there is some desire for other options.  Implementing new shapes in the viewer is the limiting factor and a bit more effort but I guess we could simply add some additional shapes that are only supported by the `plot()` function.  Of course you could do your own custom plotting of the map data and use whatever shapes you want, but I guess you're asking here about introducing integrated support.  What point shapes would you be most keen on?

**Comment by davipatti** [comment]
+1 for triangles in 3D
