### ISSUE TITLE
viewing data w discontinuous blobs - bug?!

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#68]
Hi Sam,

I've just come across the following that I think may be a bug in the Racmacs viewer:

I generated triangulation blobs for some data, with stress_lim = 0.5
When *plotting* the map, one of the blobs seems to be discontinuous with a large blob in the middle and two tiny blobs on the side of it.
When *viewing* the map, only one of these tiny blobs shows up. The large blob and the other tiny blob aren't displayed.

**Comment by shwilks** [comment]
Thanks a lot as always for spotting and reporting this, I think we found and addressed this particular issue so it should be fixed in the latest version but please reopen if not.

**Comment by CarlijnB** [comment]
Hi Sam,
Thank you for addressing this issue (and all my other issues/reports/requests).
I can confirm that in version 1.1.28 this particular issue is resolved.
Thank you for all your work on this!
(And great to see your SARS-CoV-2 preprint out)
Best wishes,
Carlijn
