### ISSUE TITLE
error lines in "plot" function?

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#69]
Hi,

Am I correct in my understanding that it is currently only possible to view error lines in the Racmacs viewer, and not with the plot function?
Would it be possible at all to add error lines as an option to the plot function?

When wanting to display two maps in a way that they can be compared - e.g. with the same scale, point size, etc - I have found the plotting function particularly useful because of the option to set the same map boundaries through xlim and ylim.
(In contrast, with the viewer, I've found it a struggle to get two maps to display at the same scale and with the same point size.)
It would be great if I could use the plotting function also to make two matching maps with their error lines!

Thank you for considering this!

Carlijn

**Comment by shwilks** [comment]
Now available with e.g.
```
plot(map, show_error_lines = TRUE)
```
