### ISSUE TITLE
table merge / sd limit?

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#77]
Hi Sam,

I hope you are well.

I've performed a merge (reoptimized merge) on some data, that includes a repeated antigen ("X").
I was surprised to find that the merge introduced lots of *s for antigen X, when the titres for X were actual numbers.
From the code on github, I figure this is because the standard deviation of these titres were above a certain number of log2 units.

Please could you confirm whether this is the case in Racmacs v1.1.12 and what that (default) limit is? (1?)
It's not mentioned in the documentation and I'm not quite sure whether the code I'm looking at on Github is the same that is implemented in v1.1.12.

Thank you,

Carlijn

**Comment by davipatti** [comment]
Hey Carlijn

You can use `RacMerge.options()` to show the standard deviation limit (in v1.1.18)

Does that work in 1.1.12?

David
