### ISSUE TITLE
agStress  when all titres to a serum are "<"

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#79]
If all measured titres to a serum are "<" values e.g. <10, then the srStress for that serum is NaN (which makes sense). But then all antigens titrated against that serum give a NaN result when agStress is used. 

I can easily workaround using removeSera, but it should be sorted out definitively at some point.

Edited to add that something similar happens if all titres to antigen are <

**Comment by shwilks** [comment]
Looking forward to the pull request :)

**Comment by drserajames** [comment]
As soon I can remember how to code and use GitHub. 

`stress(Sarah) = high`

**Comment by shwilks** [comment]
This is now fixed in v1.1.28 (I think)
