### ISSUE TITLE
procrustesMap causes R session to abort if map has duplicate names

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#80]
If a map has repeated names for antigens (or presumably sera), then running procrustesMap causes R to crash with the error 

R Session Aborted
R encountered a fatal error.
The session was terminated

**Comment by shwilks** [comment]
Thanks for the report, what do you think should be the correct behaviour? To stop with a standard error message about duplicates I guess?

**Comment by drserajames** [comment]
That sounds good. 

The long term fix would be to import antigens & sera ID information, and use that to match for procrustes. I think it's an unnecessary complication to create an internal ID when a map is created/imported, when that would solve the problem when making different versions of the same map.

**Comment by shwilks** [comment]
This will now give an error rather than crashing in v1.1.27.  Feel free to reopen an issue if you have further ideas about how to deal with this situation though.
