### ISSUE TITLE
mergeMaps does not recognise maps

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#88]
I'm using the latest version (1.1.28) and get an error when trying to merge maps

`> mergeMaps(map, map2, method="table")`
Error: Input must be an acmap object

These are maps, generated using `make.acmap`.

`> map`
\<acmap\>

...10 antigens
...10 sera
...100 optimizations
`> typeof(map)`
[1] "list"
`> map2`
\<acmap\>

...10 antigens
...10 sera
...100 optimizations
`> typeof(map2)`
[1] "list"

**Comment by shwilks** [comment]
`mergeMaps` actually expects maps to be input as a list like
```
mergeMaps(list(map, map2), method="table")
```
This is described in the documentation for mergeMaps but you're not the first one to post an issue along these lines.  Perhaps I should change the function to accept either `mergeMaps(list(map, map2), method="table")` or `mergeMaps(map, map2, method="table")`

**Comment by drserajames** [comment]
Sorry! My bad. I forgot how it works. I've merged loads of maps, so it didn't occur to me to look at the documentation.

It would help if the error said list; the error for a NULL map does, but not two maps.

```
> mergeMaps(NULL, map2, method="table")
Error: Input must be a list of acmap objects
> mergeMaps(map, map2, method="table")
Error: Input must be an acmap object
```

I'm happy with the function as it is. If I added an example to the documentation that would make it clear for a new user.
