### ISSUE TITLE
agNames causing RStudio to crash

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#89]
If `agNames(map)` is set to the wrong type, then RStudio crashes (R session aborted, terminal error etc), e.g. 

```
agNames(map) <- 1:length(agNames(map))
agNames(map) <- as.list(agNames(map))
```

My ideal behaviour would be an error message "agNames(map) requires a character vector" or something similar.

Low priority because it works fine unless the user (aka Sarah) does something silly.

Edited to say that I'd expect the same behaviour from srNames, and I imagine the other antigen and sera attributes

**Comment by shwilks** [comment]
Fixed in v1.1.30
