### ISSUE TITLE
No warning from agNames(map) <-  if names are shorter than agNames(map)

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#90]
You can set agNames(map) to be shorter and the remaining value are NA
e.g.
```
> agNames(map) <- c("each", "peach", "pear", "plum")
> agNames(map)
 [1] "each"  "peach" "pear"  "plum"  "NA"    "NA"    "NA"    "NA"    "NA"    "NA" 
```

My ideal behaviour would be a error ("name vector length does not match agNames(map) length") because I can't see when you would want the rest of the names to be NA.

Also applies to other antigen and serum attributes.

Low priority

**Comment by shwilks** [comment]
Fixed in 1.1.30
