### ISSUE TITLE
RGBA palettes applied to map result in no colour

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#95]
Using certain palettes, e.g. those output by `viridisLite` library do not colour `view(map)`, but do `plot(map)` . I think this is because they are RGBA palettes.

Ideal behaviour would be a test for a correct colour (hex code/R color name) that returned a warning that that the colours will not show in the viewer. I can imagine cases where the transparency would be useful in a static plot.

```
palette <- viridis(10)
agFill(map) <- palette
view(map)
plot(map)

palette <- substr(viridis(10), 1,7)
agFill(map) <- palette
view(map)
```

<img width="925" alt="Screenshot 2022-03-07 at 16 32 38" src="https://user-images.githubusercontent.com/18366410/157076598-9136bc21-a39e-4707-befc-8cdcdd37d8ab.png">
<img width="914" alt="Screenshot 2022-03-07 at 16 32 46" src="https://user-images.githubusercontent.com/18366410/157076605-c91814f6-474b-4423-8d8d-77b13cb96c5d.png">
<img width="929" alt="Screenshot 2022-03-07 at 16 32 58" src="https://user-images.githubusercontent.com/18366410/157076606-6b14915e-5c64-4c8f-92a5-4e99aad359e9.png">
`

**Comment by shwilks** [comment]
Fixed in v1.1.30, transparency values associated with colors will be ignored in the viewer though unless you set
```
view(map, options = list(point.opacity = "inherit"))
```
