### ISSUE TITLE
Sequences not properly imported from acmacs ace

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#97]
I'm using `read.acmap` on Eu's ace files. When there are fewer sequences than antigens then `agSequences(map)` returns a matrix with the number of rows as sequences, not as antigens. I don't think I can provide a minimal example as I don't know how to make that style ace file, but I can email an example file.

**Comment by shwilks** [comment]
Yeah, please email, thanks Sarah

**Comment by shwilks** [comment]
fixed in v1.1.31

**Comment by drserajames** [comment]
Using v1.1.31 `agSequences(map)` now looks good (although I'd prefer the missing data symbol to be different to a deletion as B/Vic has several deletion variants, but I can see that "-" makes most sense to most people).

But when I `view(map) `after running `optimizeMap(map,2,10)` on the vic table I sent you, I can't colour by sequence. The sequence option is in the colouring tab, but nothing happens when I put a number in the box. It was working in the previous version I was using (v1.1.30).

**Comment by drserajames** [comment]
Also, I don't see the sequence table when I click the QKNP button (it says "loading sequences").

**Comment by shwilks** [comment]
Thanks for reopening, I've patched a fix and will upload. You are right about "-" being confusing with delations, how about "." as a default character for missing sequence information?

**Comment by drserajames** [comment]
"." is good for me (PS I like how merged titres when there's no titration are ".")

**Comment by shwilks** [comment]
Fixed in v1.1.33, and "." is now the default
