### ISSUE TITLE
ace files compressed with brotli

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#98]
Eu has started using brotli for compression, rather than xz. This causes an error in `read.acmap`

`Error in json_to_acmap(jsondata) : Could not parse file`

I feel this falls in the category of ones I should fix myself as it's quite a niche issue.

**Comment by shwilks** [comment]
Seems like it should be an easy fix, could you point me to an example map?

**Comment by shwilks** [comment]
It wasn't too much trouble to add, should now be supported in v1.1.31
